drink_inventory/authentication/routes.py
import imp
from flask import Blueprint, render_template, request, redirect, url_for, flash
from drink_inventory.forms import UserLoginForm, UserSignupForm
from drink_inventory.models import User, db, check_password_hash, login_manager

#Import from flask login
from flask_login import login_user, logout_user, current_user, login_required

auth = Blueprint('auth', __name__, template_folder = 'auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserSignupForm()

    try:
        if request.method == "POST" and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            first_name = form.first_name.data
            last_name = form.last_name.data
            # print(email, password, first_name, last_name)

            user = User(email, first_name=first_name, last_name=last_name, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f"You have successfully created a user account {first_name}", 'user-created')

            return redirect(url_for('auth.signin'))

    except:
        raise Exception('Invalid Form Data: Please Check Your Form')

    return render_template('signup.html', form=form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == "POST" and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            # print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successfully logged in in via Email/Password', 'auth-success')
                return redirect(url_for('site.profile'))
            else:
                flash('Your Email/Password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')

    return render_template('signin.html', form=form)



@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.signin'))

drink_inventory/site/routes.py
from venv import create
from flask import Blueprint, jsonify, redirect, render_template, url_for, request
from flask_login import current_user, AnonymousUserMixin


import requests
import json

from drink_inventory.forms import DeleteDrinkForm, UserSearchForm1, AddDrinkForm, UserSearchForm2, UserSearchForm3
from drink_inventory.helpers import delete_my_drink, token_required, create_my_drink, delete_my_drink
from drink_inventory.models import db, User, Drink, drink_schema, drinks_schema

site = Blueprint('site', __name__, template_folder='site_templates')

class Anonymous(AnonymousUserMixin):
    def __init__(self):
        self.username = 'Guest'

# HOME PAGE ROUTE
@site.route('/', methods=['POST', 'GET'])
def home():
    if current_user.is_authenticated:
        # Search by Drink name
        form = UserSearchForm1()
        drink = form.drink_name.data
        req = requests.get(f"https://www.thecocktaildb.com/api/json/v1/1/search.php?s={drink}")
        data = json.loads(req.content)

        # form2 = AddDrinkForm()
        # create_my_drink() 



        # Get a Random drink
        form4 = UserSearchForm3()
        rand_drink = form4.random.data
        print(rand_drink)
        data4 = None
        if rand_drink:
            req4 = requests.get(f"https://www.thecocktaildb.com/api/json/v1/1/{rand_drink}.php")
            print(req4)
            data4 = json.loads(req4.content)
            data4 = data4['drinks']
            print(data4)
        

        # Add drink 

        form2 = AddDrinkForm()
        create_my_drink()  
    


        # form3 = UserSearchForm2()
        # ingredient = form3.ingredient_name.data
        # print(ingredient)
        # req2 = requests.get(f"https://www.thecocktaildb.com/api/json/v1/1/filter.php?i={ingredient}")
        # data2 = json.loads(req2.content)
        # drinks = data2['drinks']
        # for each in drinks:
        #     print(each['idDrink'])
        #     req3 = requests.get(f"https://www.thecocktaildb.com/api/json/v1/1/lookup.php?i={each['idDrink']}")
        #     data3 = json.loads(req3.content)
        #     print(data3)

        

        return render_template('index.html', data=data['drinks'], data4=data4, form=form, form2=form2, form4=form4)

    else:
        return redirect(url_for('auth.signin'))

# PROFILE PAGE ROUTE
@site.route('/profile', methods=['GET', 'POST'])
def profile():
        form = DeleteDrinkForm()
        
        if request.method == 'POST':
            delete_my_drink()
        owner = current_user.token
        drinks = Drink.query.filter_by(user_token = owner).all()
        response = drinks_schema.dump(drinks)
        if response:
            print(response[0]['name'])
            for drink in response:
                print(drink['name'])


        return render_template('profile.html', response=response, form=form)

drink_inventory/templates/addform.html
<form method="post">
    <div>
        <fieldset class="hidden">
            {{ form2.name(class= "form-control", value = datas['strDrink']) }}
            {{ form2.instructions(class= "form-control", value = datas['strInstructions']) }}
            {{ form2.image(class= "form-control", value = datas['strDrinkThumb']) }}
            {{ form2.ingredient1(class= "form-control", value = datas['strIngredient1']) }}
            {{ form2.measure1(class= "form-control", value = datas['strMeasure1']) }}
            {{ form2.ingredient2(class= "form-control", value = datas['strIngredient2']) }}
            {{ form2.measure2(class= "form-control", value = datas['strMeasure2']) }}
            {{ form2.ingredient3(class= "form-control", value = datas['strIngredient3']) }}
            {{ form2.measure3(class= "form-control", value = datas['strMeasure3']) }}
            {{ form2.ingredient4(class= "form-control", value = datas['strIngredient4']) }}
            {{ form2.measure4(class= "form-control", value = datas['strMeasure4']) }}
            {{ form2.ingredient5(class= "form-control", value = datas['strIngredient5']) }}
            {{ form2.measure5(class= "form-control", value = datas['strMeasure5']) }}
            {{ form2.ingredient6(class= "form-control", value = datas['strIngredient6']) }}
            {{ form2.measure6(class= "form-control", value = datas['strMeasure6']) }}
            {{ form2.ingredient7(class= "form-control", value = datas['strIngredient7']) }}
            {{ form2.measure7(class= "form-control", value = datas['strMeasure7']) }}
            {{ form2.ingredient8(class= "form-control", value = datas['strIngredient8']) }}
            {{ form2.measure8(class= "form-control", value = datas['strMeasure8']) }}
            {{ form2.ingredient9(class= "form-control", value = datas['strIngredient9']) }}
            {{ form2.measure9(class= "form-control", value = datas['strMeasure9']) }}
            {{ form2.ingredient10(class= "form-control", value = datas['strIngredient10']) }}
            {{ form2.measure10(class= "form-control", value = datas['strMeasure10']) }}
            {{ form2.ingredient11(class= "form-control", value = datas['strIngredient11']) }}
            {{ form2.measure11(class= "form-control", value = datas['strMeasure11']) }}
            {{ form2.ingredient12(class= "form-control", value = datas['strIngredient12']) }}
            {{ form2.measure12(class= "form-control", value = datas['strMeasure12']) }}
            {{ form2.ingredient13(class= "form-control", value = datas['strIngredient13']) }}
            {{ form2.measure13(class= "form-control", value = datas['strMeasure13']) }}
            {{ form2.ingredient14(class= "form-control", value = datas['strIngredient14']) }}
            {{ form2.measure14(class= "form-control", value = datas['strMeasure14']) }}
            {{ form2.ingredient15(class= "form-control", value = datas['strIngredient15']) }}
            {{ form2.measure15(class= "form-control", value = datas['strMeasure15']) }}
        </fieldset>
    </div>

    
    {{ form2.submit_button(class="btn btn-outline-success btn-block", value="Add Drink") }}
</form>

drink_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="apple-touch-icon" sizes="180x180" href="../favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="../favicon/favicon-16x16.png">
<link rel="manifest" href="../favicon/site.webmanifest">
<link rel="stylesheet" href="../static/css/main.css">
<title>cocktale</title>
</head>
<body class="bg-dark">

    <!-- NavBar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid mx-5">
            <a class="navbar-brand .text-success fs-2" href="#" id="nav-logo">
                <img src="../static/images/drinks_icon.png" alt="" width="45" height="45" class="d-inline-block align-text-center me-3" >
                cocktale
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarScroll">
                <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('site.home') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('site.profile') }}">Profile</a>
                    </li>
                </ul>
                {% if current_user.is_authenticated %}
                <a href="{{ url_for('auth.logout') }}">
                    <button class="btn btn-outline-danger mx-2" type="button" >Log Out</button>
                </a>
                {% else %}
                <a href="{{ url_for('auth.signin') }}">
                    <button class="btn btn-outline-danger mx-2" type="button" >Log In</button>
                </a>
                <a href="{{ url_for('auth.signup') }}">
                    <button class="btn btn-outline-danger mx-2" type="submit" >Sign Up</button>
                </a>
                {% endif %}
            </div>
        </div>
    </nav>


    {% block content %}       

    {% endblock content %}

    <!-- <footer class="bg-dark">
        <a href="https://www.flaticon.com/free-icons/drink" title="drink icons">Drink icons created by Freepik - Flaticon</a>
    </footer> -->

    

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

drink_inventory/templates/deleteform.html
<form method="post">
    <div>
        <fieldset class="hidden">
            {{ form.id(class= "form-control", value = drink['id']) }}
        </fieldset>
    </div>
    
    {{ form.submit_button(class="btn btn-outline-danger btn-block", value="Delete") }}
</form>

drink_inventory/templates/forms.html
<form method="post">
    <div class="form-group">
        {{ form.hidden_tag() }}
        <fieldset id="email">
            {{ form.email.label }}
            {{ form.email(class= "form-control", placeholder = "example@email.mail") }}
        </fieldset>
        </fieldset>

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class= "form-control", placeholder = "Password") }}
        </fieldset>

        {% if form.first_name %}
        <fieldset id="first-field">
            {{ form.first_name.label }}
            {{ form.first_name(class= "form-control", placeholder = "First name") }}
        </fieldset>

        <fieldset id="last-field">
            {{ form.last_name.label }}
            {{ form.last_name(class= "form-control", placeholder = "last name") }}
        </fieldset>

        {% endif %}


        <!-- Submit Button -->
        {{ form.submit_button(class="btn btn-outline-danger btn-block my-4", value="Submit") }}
    </div>
</form>

drink_inventory/templates/randomform.html
<form method="post">
    <div class="container">
        <div class="row height d-flex justify-content-center align-items-center">
            <div class="hidden">
                {{ form4.random.label }}
                {{ form4.random(class= "form-control", value = "random") }}
            </div> 
            <div class="col-md mt-2">
                {{ form4.submit_button(class="btn btn-outline-danger btn-block", value="Random") }}
            </div>
        </div>
    </div>
</form>

drink_inventory/templates/searchform.html
<form method="post">
    <div class="container">
        <div class="row height d-flex justify-content-center align-items-center">
            <div class="col-md mb-3">
                {{ form.drink_name.label }}
                {{ form.drink_name(class= "form-control", placeholder = "Search by drink name...") }}
            </div> 
            <div class="col-md mt-2">
                {{ form.submit_button(class="btn btn-outline-danger btn-block", value="Search") }}
            </div>
        </div>
    </div>
</form>